name: update-public-repo
run-name: updating public repository
on:
  push:
    branches:
      - master
jobs:
  update-public-repo:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: itskillerluc/Ark_Reseeded-PUBLIC
      - if: github.event.pull_request.head.repo.full_name != github.repository
        uses: actions/checkout@v2
        with:
          repository: itskillerluc/Ark_Reseeded-PUBLIC
          token: ${{ secrets.GH_PAT }}
          
      - run: git remote add upstream https://github.com/Itskillerluc/ark_reseeded
      - run: git pull upstream master
      - run: git push
