name: update-public-repo
run-name: updating public repository
on:
  push:
    branches:
      - master
jobs:
  update-public-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: itskillerluc/Ark_Reseeded-PUBLIC
          token: ${{ secrets.GH_PAT }}
      - run: git remote add upstream https://github.com/Itskillerluc/ark_reseeded
      - run: git pull upstream master
      - run: git push
