name: update-public-repo
run-name: updating public repository
on:
  push:
    branches:
      - master
jobs:
  update-public-repo:
    runs-on: ubuntu-latest
    steps:
      - run: echo $(ls)
      - run: cd /
      - run: ls
      - run: echo $(ls)
